name: Check for new ASF Projects

on:
  workflow_dispatch:
  schedule:
    # Every Morning at 11.00am
    - cron: "0 11 * * *"

jobs:
  generate_report:
    name: Generate Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'
      - name: Build Gradle Project
        run: ./gradlew installDist
      - name: Run API Queries
        run: build/install/new-asf-builds-query/bin/new-asf-builds-query --days=1 --develocity-url=https://ge.solutions-team.gradle.com
        env:
          API_KEY: ${{ secrets.SOLUTIONS_API_KEY }}
      - name: Create Job Summary
        run: cat report.md >> $GITHUB_STEP_SUMMARY
